import { GameTheme } from '@/shared/types';

export type GameCategory = 'all' | 'board' | 'quiz_show' | 'action' | 'seasonal' | 'strategy';

export type PlayableGameModule = 'mario-party-quiz' | 'mario-blast-classic';

export interface LauncherGame {
  id: string;
  title: string;
  shortTitle: string;
  tagline: string;
  description: string;
  category: GameCategory;
  badge: 'READY TO PLAY' | 'POPULAR' | 'IN DEVELOPMENT' | 'NEW' | 'SEASONAL';
  badgeColor: string;
  isPlayable: boolean;
  /** Only set for titles that have a siloed game module. Placeholders omit this. */
  gameModule?: PlayableGameModule;
  themeKey?: GameTheme;
  cover: {
    heroGradient: string;
    cardGradient: string;
    borderGlow: string;
    accentColor: string;
    icon: string; // Emoji or Lucide name
    coverArtEmoji: string;
    patternType: 'palm' | 'snow' | 'neon' | 'parchment' | 'space' | 'castle' | 'racing' | 'gold';
    backgroundImage?: string;
  };
  stats: {
    players: string;
    duration: string;
    questions: string;
    grades: string;
  };
  features: string[];
  powerpointInspiration: string;
  hasTeacherGuide?: boolean;
}

export const LAUNCHER_GAMES: LauncherGame[] = [
  {
    id: 'mario_party_summer',
    title: 'Super Mario Party Quiz: Summer Edition',
    shortTitle: 'Mario Party Summer',
    tagline: '60-Block Mystery Roulette & Interactive ESL Board Game',
    description: 'The flagship classroom board game! Teams take turns choosing numbered mystery blocks, answering vocabulary, unscramble, and trivia challenges, then spinning for game-changing items like Stars, Boo Steals, and Bowser Revolutions.',
    category: 'board',
    badge: 'READY TO PLAY',
    badgeColor: 'bg-gradient-to-r from-amber-500 to-yellow-400 text-slate-950 shadow-yellow-500/30',
    isPlayable: true,
    gameModule: 'mario-party-quiz',
    themeKey: 'summer',
    hasTeacherGuide: true,
    cover: {
      heroGradient: 'from-amber-600 via-orange-600 to-yellow-500',
      cardGradient: 'from-amber-950/90 via-slate-900/95 to-orange-950/80',
      borderGlow: 'hover:border-amber-400/80 hover:shadow-[0_0_30px_rgba(245,158,11,0.35)]',
      accentColor: '#f59e0b',
      icon: 'Sun',
      coverArtEmoji: '🏖️',
      patternType: 'palm',
      backgroundImage: '/assets/boxart/boxart_supersummerblast.jpeg',
    },
    stats: {
      players: '2 – 6 Teams',
      duration: '20 – 45 Min',
      questions: '60 Curated Blocks',
      grades: 'Elementary & JHS',
    },
    features: [
      '60 Curated Summer ESL & General Trivia Questions',
      '6-Card Mystery Roulette Draw System',
      'Double Turns, Boo Stealing & Bowser Revolutions',
      'Star captures, coin races, and classroom-safe item cards',
    ],
    powerpointInspiration: 'Upgrades the 50-slide Mario PPT with real sound effects, audio, and coin physics',
  },
  {
    id: 'mario_party_winter',
    title: 'Super Mario Party Quiz: Holiday Edition',
    shortTitle: 'Mario Party Holiday',
    tagline: 'Festive Winter Mystery Board with Snowy Surprises',
    description: 'A cozy holiday edition featuring winter-themed trivia, holiday vocabulary, Christmas carol sing-along rewards, and chilly Bowser Blizzard events.',
    category: 'seasonal',
    badge: 'READY TO PLAY',
    badgeColor: 'bg-gradient-to-r from-cyan-400 to-blue-500 text-slate-950 shadow-cyan-500/30',
    isPlayable: true,
    gameModule: 'mario-party-quiz',
    themeKey: 'christmas',
    hasTeacherGuide: true,
    cover: {
      heroGradient: 'from-cyan-700 via-blue-700 to-indigo-900',
      cardGradient: 'from-blue-950/90 via-slate-900/95 to-cyan-950/80',
      borderGlow: 'hover:border-cyan-400/80 hover:shadow-[0_0_30px_rgba(34,211,238,0.35)]',
      accentColor: '#38bdf8',
      icon: 'Snowflake',
      coverArtEmoji: '❄️',
      patternType: 'snow',
      backgroundImage: '/assets/boxart/boxart_superwinterblast.jpeg',
    },
    stats: {
      players: '2 – 6 Teams',
      duration: '20 – 45 Min',
      questions: '60 Holiday Blocks',
      grades: 'All Grades',
    },
    features: [
      'Festive Christmas & Winter Holiday Questions',
      'Carol Sing-Along Surprise Rewards',
      'Winterized Soundboard & Particle Engine',
      'Star captures, coin races, and classroom-safe item cards',
      'Snowy Visual Theme with Frost Effects',
    ],
    powerpointInspiration: 'Replaces seasonal winter PPT games with animated snow and holiday music',
  },
  {
    id: 'mario_blast_classic',
    title: 'Mario Blast Classic',
    shortTitle: 'Mario Blast Classic',
    tagline: 'Have You Ever…? Live Classroom Race & Mystery Cards',
    description:
      'The original Blast loop, rebuilt. One team picks the block, the whole class can answer, and correct teams draw from six mystery cards. Race for first pick — Gold Stars, Mystery Blocks, and Bowser cards can slam the round shut.',
    category: 'board',
    badge: 'NEW',
    badgeColor: 'bg-gradient-to-r from-rose-500 to-amber-400 text-slate-950 shadow-rose-500/30',
    isPlayable: true,
    gameModule: 'mario-blast-classic',
    themeKey: 'classic',
    hasTeacherGuide: true,
    cover: {
      heroGradient: 'from-rose-600 via-orange-500 to-amber-400',
      cardGradient: 'from-rose-950/90 via-slate-900/95 to-amber-950/80',
      borderGlow: 'hover:border-rose-400/80 hover:shadow-[0_0_30px_rgba(244,63,94,0.35)]',
      accentColor: '#fb7185',
      icon: 'Star',
      coverArtEmoji: '⭐',
      patternType: 'gold',
      backgroundImage: '/assets/boxart/boxart_superquizclassic.jpeg',
    },
    stats: {
      players: '2 – 6 Teams',
      duration: '20 – 45 Min',
      questions: '60 Have You Ever',
      grades: 'JHS Present Perfect',
    },
    features: [
      'Any team can answer — host clicks the winner, then a card',
      'Six mystery cards per question; one draw per team',
      'Rare round-enders: Gold Star, Bowser Revolution, Bowser’s Fury, Piranha Plant',
      'Same Mario Party items as Summer & Holiday, remapped for live play',
    ],
    powerpointInspiration: 'Recreates the original Have You Ever Mario Party PPT with live multi-team answering',
  },
  {
    id: 'mario_halloween_blast',
    title: 'Super Halloween Blast',
    shortTitle: 'Halloween Blast',
    tagline: 'Spooky Mystery Blocks, Ghost Hunts & Haunted Cards',
    description:
      'A coming-soon seasonal Mario Blast night. Teams pick blocks under a haunted sky, race to answer, and draw from a deck of haunted block cards — the twist we’ll cook up for October classrooms.',
    category: 'seasonal',
    badge: 'IN DEVELOPMENT',
    badgeColor: 'bg-gradient-to-r from-orange-500 to-purple-600 text-white shadow-orange-500/30',
    isPlayable: false,
    cover: {
      heroGradient: 'from-orange-700 via-purple-800 to-slate-950',
      cardGradient: 'from-orange-950/90 via-slate-900/95 to-purple-950/80',
      borderGlow: 'hover:border-orange-400/80 hover:shadow-[0_0_30px_rgba(249,115,22,0.35)]',
      accentColor: '#f97316',
      icon: 'Ghost',
      coverArtEmoji: '🎃',
      patternType: 'castle',
      backgroundImage: '/assets/boxart/boxart_superhalloweenblast.jpeg',
    },
    stats: {
      players: '2 – 6 Teams',
      duration: '20 – 45 Min',
      questions: '60 Spooky Blocks',
      grades: 'Elementary & JHS',
    },
    features: [
      'Haunted Block Cards',
      'Halloween mystery board & seasonal trivia',
      'Ghost hunts, pumpkin coins, and classroom-safe scares',
      'Coming soon as a seasonal Mario Blast edition',
    ],
    powerpointInspiration: 'A Halloween classroom PPT upgrade with haunted blocks instead of static slides',
  },
  {
    id: 'jeopardy_showdown',
    title: 'Jeopardy: ALT Big Board Showdown',
    shortTitle: 'Classroom Jeopardy',
    tagline: '5x5 Grid Trivia Show with Wagers & Daily Doubles',
    description: 'Transform your classroom into a live TV studio. Teams choose categories and coin values from $100 to $500, with hidden Daily Doubles and a high-stakes Final Jeopardy wager round.',
    category: 'quiz_show',
    badge: 'IN DEVELOPMENT',
    badgeColor: 'bg-indigo-600/80 text-indigo-100 border border-indigo-400/40',
    isPlayable: false,
    cover: {
      heroGradient: 'from-indigo-700 via-blue-800 to-slate-900',
      cardGradient: 'from-indigo-950/80 via-slate-900/95 to-blue-950/80',
      borderGlow: 'hover:border-indigo-400/60 hover:shadow-[0_0_25px_rgba(99,102,241,0.25)]',
      accentColor: '#6366f1',
      icon: 'Tv',
      coverArtEmoji: '📺',
      patternType: 'neon',
    },
    stats: {
      players: '2 – 8 Teams',
      duration: '25 – 40 Min',
      questions: '25 – 30 Clues',
      grades: 'JHS & High School',
    },
    features: [
      '5 Custom Categories with $100–$500 Stakes',
      'Secret Hidden Daily Doubles with Sound Cues',
      'Final Jeopardy Music Timer & Wager System',
      'One-Click Category Deck Importer',
    ],
    powerpointInspiration: 'Upgrades the fragile hyperlink-based PowerPoint Jeopardy games',
  },
  {
    id: 'bomb_game',
    title: 'The Bomb Game: Explosive Countdown',
    shortTitle: 'The Bomb Game',
    tagline: 'Rapid-Fire Vocabulary Defusal & Hot Potato Action',
    description: 'The legendary ESL classroom favorite re-engineered! Students solve rapid-fire target language drills before the ticking dynamite detonates. Pass the bomb or earn defusal shields.',
    category: 'action',
    badge: 'IN DEVELOPMENT',
    badgeColor: 'bg-red-600/80 text-red-100 border border-red-400/40',
    isPlayable: false,
    cover: {
      heroGradient: 'from-red-700 via-rose-800 to-slate-900',
      cardGradient: 'from-red-950/80 via-slate-900/95 to-rose-950/80',
      borderGlow: 'hover:border-red-400/60 hover:shadow-[0_0_25px_rgba(239,68,68,0.25)]',
      accentColor: '#ef4444',
      icon: 'Flame',
      coverArtEmoji: '💣',
      patternType: 'neon',
    },
    stats: {
      players: '2 – 6 Teams',
      duration: '15 – 30 Min',
      questions: '40 Flash Cards',
      grades: 'Elementary & JHS',
    },
    features: [
      'Heart-Pounding Ticking Sound & Audio Countdown',
      'Defusal Shields, Point Steals & Sudden Detonations',
      'High-Paced 15-Second Turn Clocks',
      'Engaging for Energetic Afternoon Classes',
    ],
    powerpointInspiration: 'Replaces classic Flash/PPT bomb games with modern web audio and animations',
  },
  {
    id: 'monster_catcher',
    title: 'Monster Catcher: Pokemon ESL Arena',
    shortTitle: 'Monster Catcher Arena',
    tagline: 'Answer Questions to Power Up Attacks & Catch Wild Beasts',
    description: 'Turn grammar and vocabulary into epic turn-based monster battles! Correct answers charge elemental energy (Fire, Water, Grass, Electric) to defeat and catch classroom boss monsters.',
    category: 'action',
    badge: 'IN DEVELOPMENT',
    badgeColor: 'bg-emerald-600/80 text-emerald-100 border border-emerald-400/40',
    isPlayable: false,
    cover: {
      heroGradient: 'from-emerald-700 via-teal-800 to-slate-900',
      cardGradient: 'from-emerald-950/80 via-slate-900/95 to-teal-950/80',
      borderGlow: 'hover:border-emerald-400/60 hover:shadow-[0_0_25px_rgba(16,185,129,0.25)]',
      accentColor: '#10b981',
      icon: 'Swords',
      coverArtEmoji: '⚡',
      patternType: 'neon',
    },
    stats: {
      players: '2 – 6 Teams',
      duration: '25 – 45 Min',
      questions: '50 Battle Clues',
      grades: 'Elementary & JHS',
    },
    features: [
      'Turn-Based Elemental Battle Engine',
      'HP Bars, Attack Animations & Capture Spheres',
      'Wild Creature Dex for Class Progress',
      'Grammar Accuracy Multipliers',
    ],
    powerpointInspiration: 'Brings fan-favorite Pokemon PPT templates into a robust interactive app',
  },
  {
    id: 'mystery_box',
    title: 'Mystery Box & The Lucky Wheel',
    shortTitle: 'Mystery Box Show',
    tagline: 'Keep or Trade? The High-Stakes Classroom Game Show',
    description: 'Teams answer questions to earn mysterious sealed boxes. Do they KEEP their mystery box or TRADE with the leading team? Watch out for the Bankrupt trap or the Golden Jackpots!',
    category: 'board',
    badge: 'IN DEVELOPMENT',
    badgeColor: 'bg-purple-600/80 text-purple-100 border border-purple-400/40',
    isPlayable: false,
    cover: {
      heroGradient: 'from-purple-700 via-violet-800 to-slate-900',
      cardGradient: 'from-purple-950/80 via-slate-900/95 to-violet-950/80',
      borderGlow: 'hover:border-purple-400/60 hover:shadow-[0_0_25px_rgba(168,85,247,0.25)]',
      accentColor: '#a855f7',
      icon: 'Gift',
      coverArtEmoji: '🎁',
      patternType: 'gold',
    },
    stats: {
      players: '2 – 6 Teams',
      duration: '20 – 35 Min',
      questions: '36 Prize Boxes',
      grades: 'All Grades',
    },
    features: [
      'Interactive "Keep It or Trade It" Decisions',
      'Spinning Carnival Multiplier Wheel',
      'Hilarious Booby Prizes & Giant Point Swaps',
      'Guaranteed Laughs and Maximum Suspense',
    ],
    powerpointInspiration: 'Upgrades the legendary Deal or No Deal / Mystery Box PPT games',
  },
  {
    id: 'treasure_island',
    title: 'Treasure Island: Gold Rush Pirates',
    shortTitle: 'Treasure Island',
    tagline: 'Coordinate Grid Exploration & Buried Booty Battles',
    description: 'Sail across an uncharted island grid (A1 to F6). Solve questions to excavate coordinates on the pirate map, discovering buried gold, cursed skulls, or ship-sinking krakens.',
    category: 'strategy',
    badge: 'IN DEVELOPMENT',
    badgeColor: 'bg-yellow-600/80 text-yellow-100 border border-yellow-400/40',
    isPlayable: false,
    cover: {
      heroGradient: 'from-amber-700 via-yellow-800 to-slate-900',
      cardGradient: 'from-amber-950/80 via-slate-900/95 to-yellow-950/80',
      borderGlow: 'hover:border-yellow-400/60 hover:shadow-[0_0_25px_rgba(234,179,8,0.25)]',
      accentColor: '#eab308',
      icon: 'Compass',
      coverArtEmoji: '🏴‍☠️',
      patternType: 'parchment',
    },
    stats: {
      players: '2 – 6 Teams',
      duration: '20 – 40 Min',
      questions: '36 Grid Tiles',
      grades: 'Elementary & JHS',
    },
    features: [
      'Cartoony Parchment Island Grid Map',
      'Battleship-style Coordinate Calling (Great for Alphabet & Numbers)',
      'Pirate Cannons & Ghost Ship Raids',
      'Treasure Chest Digging Animations',
    ],
    powerpointInspiration: 'Re-imagines the classic Battleship and Pirate Island PPT games',
  },
  {
    id: 'vocabulary_tycoon',
    title: 'Vocabulary Tycoon: City Builder',
    shortTitle: 'Vocabulary Tycoon',
    tagline: 'Invest Points to Construct Skyscrapers & Landmarks',
    description: 'A strategic empire builder where correct answers yield building materials. Teams compete to construct the most valuable classroom metropolis with solar farms, airports, and towers.',
    category: 'strategy',
    badge: 'IN DEVELOPMENT',
    badgeColor: 'bg-blue-600/80 text-blue-100 border border-blue-400/40',
    isPlayable: false,
    cover: {
      heroGradient: 'from-blue-700 via-sky-800 to-slate-900',
      cardGradient: 'from-blue-950/80 via-slate-900/95 to-sky-950/80',
      borderGlow: 'hover:border-blue-400/60 hover:shadow-[0_0_25px_rgba(59,130,246,0.25)]',
      accentColor: '#3b82f6',
      icon: 'Building2',
      coverArtEmoji: '🏙️',
      patternType: 'neon',
    },
    stats: {
      players: '2 – 5 Teams',
      duration: '30 – 50 Min',
      questions: '45 Economics Cards',
      grades: 'JHS & High School',
    },
    features: [
      'Isometric City Grid with Live Visual Upgrades',
      'Passive Point Yields from Completed Buildings',
      'Natural Disasters and Insurance Quiz Challenges',
      'Strategic Decision-Making for Older Students',
    ],
    powerpointInspiration: 'Replaces complex Monopoly PPT games with clean automated mechanics',
  },
  {
    id: 'alien_invasion',
    title: 'Alien Invasion: Space Defense',
    shortTitle: 'Alien Invasion',
    tagline: 'Cooperative Class Defense Against Incoming Space Fleets',
    description: 'All teams unite against an alien mothership! Each round, students answer spelling and sentence patterns to charge photon lasers, lower alien shields, and defend Earth.',
    category: 'action',
    badge: 'IN DEVELOPMENT',
    badgeColor: 'bg-fuchsia-600/80 text-fuchsia-100 border border-fuchsia-400/40',
    isPlayable: false,
    cover: {
      heroGradient: 'from-fuchsia-700 via-purple-800 to-slate-900',
      cardGradient: 'from-fuchsia-950/80 via-slate-900/95 to-purple-950/80',
      borderGlow: 'hover:border-fuchsia-400/60 hover:shadow-[0_0_25px_rgba(217,70,239,0.25)]',
      accentColor: '#d946ef',
      icon: 'Rocket',
      coverArtEmoji: '🛸',
      patternType: 'space',
    },
    stats: {
      players: 'Whole Class / Teams',
      duration: '15 – 30 Min',
      questions: '40 Defense Waves',
      grades: 'Elementary & JHS',
    },
    features: [
      'Retro Sci-Fi Arcade Aesthetics & Sound FX',
      'Cooperative Classroom vs Alien Boss Gameplay',
      'Wave-Based Difficulty Scaling',
      'Laser Blast Visual Effects on Correct Answers',
    ],
    powerpointInspiration: 'Modernizes Space Invaders and Boss Battle PowerPoint activities',
  },
  {
    id: 'grammar_dungeon',
    title: 'Grammar Dungeon: Castle Quest',
    shortTitle: 'Grammar Dungeon',
    tagline: 'Dungeon Crawling RPG with Spellcasting Grammar Puzzles',
    description: 'Descend through 10 torchlit dungeon floors. Defeat goblins, unlock mimic chests, and solve irregular verb spellcasting riddles to reach the ancient Dragon Throne.',
    category: 'strategy',
    badge: 'IN DEVELOPMENT',
    badgeColor: 'bg-stone-600/80 text-stone-200 border border-stone-400/40',
    isPlayable: false,
    cover: {
      heroGradient: 'from-stone-700 via-slate-800 to-zinc-950',
      cardGradient: 'from-stone-950/90 via-slate-900/95 to-zinc-950/80',
      borderGlow: 'hover:border-amber-400/50 hover:shadow-[0_0_25px_rgba(245,158,11,0.2)]',
      accentColor: '#d97706',
      icon: 'Shield',
      coverArtEmoji: '🏰',
      patternType: 'castle',
    },
    stats: {
      players: '2 – 6 Teams',
      duration: '25 – 45 Min',
      questions: '35 Dungeon Rooms',
      grades: 'JHS & High School',
    },
    features: [
      'Branching Path Choice (Left, Right, or Secret Door)',
      'RPG Inventory (Health Potions, Magic Scrolls, Keys)',
      'Sentence Structure Boss Fights',
      'Atmospheric Torchlight Visual Effects',
    ],
    powerpointInspiration: 'Brings text-heavy RPG PowerPoint templates into an immersive fantasy UI',
  },
  {
    id: 'grand_prix',
    title: 'Speed Runners: ESL Grand Prix',
    shortTitle: 'Grand Prix Racing',
    tagline: 'Fastest Finger First! High-Octane Circuit Racing',
    description: 'A lightning-paced racing game where response speed matters. Correct answers boost kart speed; question streaks trigger turbo mushrooms, while wrong answers trigger banana spins!',
    category: 'action',
    badge: 'IN DEVELOPMENT',
    badgeColor: 'bg-lime-600/80 text-lime-100 border border-lime-400/40',
    isPlayable: false,
    cover: {
      heroGradient: 'from-lime-600 via-emerald-800 to-slate-900',
      cardGradient: 'from-lime-950/80 via-slate-900/95 to-emerald-950/80',
      borderGlow: 'hover:border-lime-400/60 hover:shadow-[0_0_25px_rgba(132,204,22,0.25)]',
      accentColor: '#84cc16',
      icon: 'Zap',
      coverArtEmoji: '🏎️',
      patternType: 'racing',
    },
    stats: {
      players: '2 – 6 Karts',
      duration: '15 – 25 Min',
      questions: '30 Speed Laps',
      grades: 'All Grades',
    },
    features: [
      'Live Track Position Bar with 6 Animated Karts',
      'Speed Streak Turbos & Banana Peel Hazards',
      'Ideal for Quick 15-Minute Warmups',
      'Checkered Flag Victory Podium',
    ],
    powerpointInspiration: 'Replaces Mario Kart racing PPT games with real-time synchronized track physics',
  },
  {
    id: 'auction_house',
    title: 'Classroom Auction House: Antique Antics',
    shortTitle: 'Auction House',
    tagline: 'Bid Points on Mystery Antiques, Masterpieces & Counterfeits',
    description: 'Students earn bank balances through grammar challenges, then enter a live auction to bid on shrouded mystery museum lots. Will their lot be a $1,000,000 masterpiece or a counterfeit banana?',
    category: 'strategy',
    badge: 'IN DEVELOPMENT',
    badgeColor: 'bg-amber-600/80 text-amber-100 border border-amber-400/40',
    isPlayable: false,
    cover: {
      heroGradient: 'from-amber-700 via-stone-800 to-slate-900',
      cardGradient: 'from-amber-950/80 via-slate-900/95 to-stone-950/80',
      borderGlow: 'hover:border-amber-400/60 hover:shadow-[0_0_25px_rgba(245,158,11,0.25)]',
      accentColor: '#d97706',
      icon: 'Gavel',
      coverArtEmoji: '🏛️',
      patternType: 'gold',
    },
    stats: {
      players: '2 – 6 Teams',
      duration: '25 – 45 Min',
      questions: '25 Auction Lots',
      grades: 'JHS & High School',
    },
    features: [
      'Live Gavel Tapping Sound & Countdown ("Going once, going twice...")',
      'Appraisal Reveal Stage (Authentic vs Fake Counterfeits)',
      'Teaches Numbers, Currency & Critical Thinking',
      'Exciting Economic Risk-Reward Gameplay',
    ],
    powerpointInspiration: 'Upgrades the popular Auction / Bidding classroom PPT game',
  },
];
